'use strict';var aa,ba=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function p(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.fa=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ma(){this.o=!1;this.l=null;this.h=void 0;this.g=1;this.v=this.i=0;this.m=null}function na(a){if(a.o)throw new TypeError("Generator is already running");a.o=!0}ma.prototype.u=function(a){this.h=a};function oa(a,b){a.m={W:b,isException:!0};a.g=a.i||a.v}
ma.prototype.return=function(a){this.m={return:a};this.g=this.v};function r(a,b,c){a.g=c;return{value:b}}function pa(a,b){a.g=b;a.i=0}function qa(a){a.i=0;var b=a.m.W;a.m=null;return b}function ra(a){this.g=new ma;this.h=a}function sa(a,b){na(a.g);var c=a.g.l;if(c)return ta(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return ua(a)}
function ta(a,b,c,d){try{var e=b.call(a.g.l,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.o=!1,e;var f=e.value}catch(g){return a.g.l=null,oa(a.g,g),ua(a)}a.g.l=null;d.call(a.g,f);return ua(a)}
function ua(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.o=!1,{value:b.value,done:!1}}catch(c){a.g.h=void 0,oa(a.g,c)}a.g.o=!1;if(a.g.m){b=a.g.m;a.g.m=null;if(b.isException)throw b.W;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function va(a){this.next=function(b){na(a.g);a.g.l?b=ta(a,a.g.l.next,b,a.g.u):(a.g.u(b),b=ua(a));return b};this.throw=function(b){na(a.g);a.g.l?b=ta(a,a.g.l["throw"],b,a.g.u):(oa(a.g,b),b=ua(a));return b};this.return=function(b){return sa(a,b)};this[Symbol.iterator]=function(){return this}}function wa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function t(a){return wa(new va(new ra(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ka?function(b,c){try{return ka(b,c),!0}catch(d){return!1}}:null});
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ca(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return xa(la(this))}});return a});function xa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
l("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.u=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.m()})}this.g.push(g)};var e=ea.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(m){this.l(m)}}}this.g=null};c.prototype.l=function(g){this.i(function(){throw g;})};b.prototype.l=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.C),reject:g(this.m)}};b.prototype.C=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.G(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.B(g):this.o(g)}};
b.prototype.B=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}typeof h=="function"?this.H(h,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;this.h===2&&this.F();this.D()};b.prototype.F=function(){var g=this;e(function(){if(g.A()){var h=ea.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.D=function(){if(this.g!=null){for(var g=0;g<this.g.length;++g)f.h(this.g[g]);this.g=null}};var f=new c;
b.prototype.G=function(g){var h=this.l();g.K(h.resolve,h.reject)};b.prototype.H=function(g,h){var k=this.l();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(g,h){function k(x,z){return typeof x=="function"?function(G){try{m(x(G))}catch(C){n(C)}}:z}var m,n,w=new b(function(x,z){m=x;n=z});this.K(k(g,m),k(h,n));return w};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.K=function(g,h){function k(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;
default:throw Error("Unexpected state: "+m.h);}}var m=this;this.g==null?f.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).K(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function w(G){return function(C){x[G]=C;z--;z==0&&m(x)}}var x=[],z=0;do x.push(void 0),z++,d(k.value).K(w(x.length-1),n),k=h.next();while(!k.done)})};
return b});l("Object.setPrototypeOf",function(a){return a||ka});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var ya=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||ya});
l("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(w){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return xa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var w=n[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:m,list:n,index:h,entry:w}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(w){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function za(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return za(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Aa=this||self;function Ba(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=Aa,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function Ca(a){return a};var Da=Ba(610401301,!1),Ea=Ba(748402147,!0),Fa=Ba(824648567,Ba(1,!0));function Ga(){return typeof BigInt==="function"};function Ha(a){a.ba=!0;return a};var Ia=Ha(function(a){return typeof a==="number"}),Ja=Ha(function(a){return typeof a==="string"}),Ka=Ha(function(a){return typeof a==="boolean"});var La=typeof Aa.BigInt==="function"&&typeof Aa.BigInt(0)==="bigint";function Ma(a){var b=a;if(Ja(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Ia(b)&&!Number.isSafeInteger(b))throw Error(String(b));return La?BigInt(a):a=Ka(a)?a?"1":"0":Ja(a)?a.trim()||"0":String(a)}var Sa=Ha(function(a){return La?a>=Na&&a<=Oa:a[0]==="-"?Pa(a,Qa):Pa(a,Ra)}),Qa=Number.MIN_SAFE_INTEGER.toString(),Na=La?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ra=Number.MAX_SAFE_INTEGER.toString(),Oa=La?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Pa(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Ta=typeof Uint8Array.prototype.slice==="function",v=0,y=0,Ua;function Va(a){var b=a>>>0;v=b;y=(a-b)/4294967296>>>0}function Wa(a){if(a<0){Va(-a);var b=q(Xa(v,y));a=b.next().value;b=b.next().value;v=a>>>0;y=b>>>0}else Va(a)}function Ya(a){var b=Ua||(Ua=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);y=0;v=b.getUint32(0,!0)}function Za(a){var b=Ua||(Ua=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);v=b.getUint32(0,!0);y=b.getUint32(4,!0)}
function $a(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:ab(a,b)}function bb(a,b){return Ma(Ga()?BigInt.asUintN(64,(BigInt(b>>>0)<<BigInt(32))+BigInt(a>>>0)):ab(a,b))}function cb(a,b){var c=b&2147483648;c&&(a=~a+1>>>0,b=~b>>>0,a==0&&(b=b+1>>>0));a=$a(a,b);return typeof a==="number"?c?-a:a:c?"-"+a:a}function db(a,b){return Ga()?Ma(BigInt.asIntN(64,(BigInt.asUintN(32,BigInt(b))<<BigInt(32))+BigInt.asUintN(32,BigInt(a)))):Ma(eb(a,b))}
function ab(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Ga()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+fb(c)+fb(a));return c}function fb(a){a=String(a);return"0000000".slice(a.length)+a}
function eb(a,b){b&2147483648?Ga()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Xa(a,b)),a=b.next().value,b=b.next().value,a="-"+ab(a,b)):a=ab(a,b);return a}
function gb(a){if(a.length<16)Wa(Number(a));else if(Ga())a=BigInt(a),v=Number(a&BigInt(4294967295))>>>0,y=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");y=v=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),y*=1E6,v=v*1E6+d,v>=4294967296&&(y+=Math.trunc(v/4294967296),y>>>=0,v>>>=0);b&&(b=q(Xa(v,y)),a=b.next().value,b=b.next().value,v=a,y=b)}}function Xa(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function hb(a,b){this.h=a>>>0;this.g=b>>>0}function ib(a){return a.h===0?new hb(0,1+~a.g):new hb(~a.h+1,~a.g)}function jb(a){a=BigInt.asUintN(64,a);return new hb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}function kb(a){if(!a)return lb||(lb=new hb(0,0));if(!/^\d+$/.test(a))return null;gb(a);return new hb(v,y)}var lb;function mb(a,b){this.h=a>>>0;this.g=b>>>0}function nb(a){a=BigInt.asUintN(64,a);return new mb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}
function ob(a){if(!a)return pb||(pb=new mb(0,0));if(!/^-?\d+$/.test(a))return null;gb(a);return new mb(v,y)}var pb;function qb(){throw Error("Invalid UTF8");}function rb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var sb=void 0,tb,ub=typeof TextDecoder!=="undefined",vb,wb=typeof String.prototype.isWellFormed==="function",xb=typeof TextEncoder!=="undefined";
function yb(a){var b=!1;b=b===void 0?!1:b;if(xb){if(b&&(wb?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(vb||(vb=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function zb(a){Aa.setTimeout(function(){throw a;},0)};function Ab(){var a=Aa.navigator;return a&&(a=a.userAgent)?a:""}var Bb,Cb=Aa.navigator;Bb=Cb?Cb.userAgentData||null:null;var Db={},Eb=null;function Fb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;Gb(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function Gb(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=Eb[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}Hb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function Hb(){if(!Eb){Eb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));Db[c]=d;for(var e=0;e<d.length;e++){var f=d[e];Eb[f]===void 0&&(Eb[f]=e)}}}};var Ib=typeof Uint8Array!=="undefined",Jb=!(Da&&Bb&&Bb.brands.length>0?0:Ab().indexOf("Trident")!=-1||Ab().indexOf("MSIE")!=-1)&&typeof btoa==="function",Kb=/[-_.]/g,Lb={"-":"+",_:"/",".":"="};function Mb(a){return Lb[a]||""}function Nb(a){if(!Jb)return Fb(a);a=Kb.test(a)?a.replace(Kb,Mb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Ob={};function Pb(a,b){Qb(b);this.g=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function Rb(){return Sb||(Sb=new Pb(null,Ob))}function Tb(a){Qb(Ob);var b=a.g;b=b==null||Ib&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Nb(b):null;return b==null?b:a.g=b}var Sb;function Qb(a){if(a!==Ob)throw Error("illegal external caller");};function Vb(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.g=b}
function Wb(a,b){if(typeof a==="string")return new Vb(Nb(a),b);if(Array.isArray(a))return new Vb(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Vb(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Vb(a,!1);if(a.constructor===Pb)return b=Tb(a)||new Uint8Array(0),new Vb(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Vb(a,!1);throw Error();};function Xb(a,b,c,d){this.h=null;this.m=!1;this.g=this.i=this.l=0;this.init(a,b,c,d)}Xb.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.J===void 0?!1:e.J;e=e.L===void 0?!1:e.L;this.J=d;this.L=e;a&&(a=Wb(a,this.L),this.h=a.buffer,this.m=a.g,this.l=b||0,this.i=c!==void 0?this.l+c:this.h.length,this.g=this.l)};Xb.prototype.clear=function(){this.h=null;this.m=!1;this.g=this.i=this.l=0;this.J=!1};
function Yb(a,b){var c=0,d=0,e=0,f=a.h,g=a.g;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);if(e>32)for(d|=(h&127)>>4,e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;Zb(a,g);if(!(h&128))return b(c>>>0,d>>>0);throw Error();}function Zb(a,b){a.g=b;if(b>a.i)throw Error();}
function $b(a){var b=a.h,c=a.g,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw Error();Zb(a,c);return e}function ac(a){return $b(a)>>>0}function bc(a){a=ac(a);return a>>>1^-(a&1)}function cc(a){return Yb(a,cb)}function dc(a){return Yb(a,db)}
function ec(a){var b=a.h,c=a.g,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];Zb(a,a.g+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}function fc(a){var b=ec(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function hc(a){var b=ec(a),c=ec(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}
function ic(a){for(var b=0,c=a.g,d=c+10,e=a.h;c<d;){var f=e[c++];b|=f;if((f&128)===0)return Zb(a,c),!!(b&127)}throw Error();}function jc(a){return $b(a)}function kc(a,b){if(b<0)throw Error();var c=a.g;b=c+b;if(b>a.i)throw Error();a.g=b;return c}function lc(a,b){if(b==0)return Rb();var c=kc(a,b);a.J&&a.m?c=a.h.subarray(c,c+b):(a=a.h,b=c+b,c=c===b?new Uint8Array(0):Ta?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?Rb():new Pb(c,Ob)}var mc=[],nc=void 0;function oc(){this.g=[]}oc.prototype.length=function(){return this.g.length};oc.prototype.end=function(){var a=this.g;this.g=[];return a};function pc(a,b,c){for(;c>0||b>127;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function qc(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function rc(a,b){if(b>=0)qc(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function A(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function sc(a,b,c,d){if(mc.length){var e=mc.pop();e.init(a,b,c,d);a=e}else a=new Xb(a,b,c,d);this.h=a;this.l=this.h.g;this.g=this.i=-1;this.setOptions(d)}sc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.T=a.T===void 0?!1:a.T};function tc(a,b,c,d){if(uc.length){var e=uc.pop();e.setOptions(d);e.h.init(a,b,c,d);return e}return new sc(a,b,c,d)}function vc(a){a.h.clear();a.i=-1;a.g=-1;uc.length<100&&uc.push(a)}
function wc(a){var b=a.h;if(b.g==b.i)return!1;a.l=a.h.g;var c=ac(a.h);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw Error();if(b<1)throw Error();a.i=b;a.g=c;return!0}function xc(a){switch(a.g){case 0:a.g!=0?xc(a):ic(a.h);break;case 1:a=a.h;Zb(a,a.g+8);break;case 2:if(a.g!=2)xc(a);else{var b=ac(a.h);a=a.h;Zb(a,a.g+b)}break;case 5:a=a.h;Zb(a,a.g+4);break;case 3:b=a.i;do{if(!wc(a))throw Error();if(a.g==4){if(a.i!=b)throw Error();break}xc(a)}while(1);break;default:throw Error();}}
function yc(a,b,c){var d=a.h.i,e=ac(a.h);e=a.h.g+e;var f=e-d;f<=0&&(a.h.i=e,c(b,a,void 0,void 0,void 0),f=e-a.h.g);if(f)throw Error();a.h.g=e;a.h.i=d;return b}
function zc(a){var b=ac(a.h);a=a.h;var c=kc(a,b);a=a.h;if(ub){var d=a,e;(e=tb)||(e=tb=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(sb===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),sb=!0}catch(n){sb=!1}}!sb&&(tb=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?qb():(k=a[f++],h<194||(k&192)!==128?(f--,qb()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?qb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,qb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?qb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,qb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):qb(),c.length>=8192&&(g=rb(g,c),c.length=0);f=rb(g,c)}return f}function Ac(a){var b=ac(a.h);return lc(a.h,b)}
function Bc(a,b,c){var d=ac(a.h);for(d=a.h.g+d;a.h.g<d;)c.push(b(a.h))}var uc=[];function Cc(){this.i=[];this.h=0;this.g=new oc}function Dc(a,b){b.length!==0&&(a.i.push(b),a.h+=b.length)}function Ec(a,b){B(a,b,2);b=a.g.end();Dc(a,b);b.push(a.h);return b}function Fc(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}function B(a,b,c){qc(a.g,b*8+c)}function Gc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),rc(a.g,c))}function Hc(a,b,c){B(a,b,2);qc(a.g,c.length);Dc(a,a.g.end());Dc(a,c)}
function Ic(a,b,c,d){c!=null&&(b=Ec(a,b),d(c,a),Fc(a,b))}function Jc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?kb(a.substring(1)):kb(a)}};var Kc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Lc(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Mc=Lc("jas",void 0,!0),Nc=Lc(void 0,"1oa"),Oc=Lc(void 0,Symbol()),Pc=Lc(void 0,"0ubs"),Qc=Lc(void 0,"0ubsb"),Rc=Lc(void 0,"0actk"),Sc=Lc("m_m","ca",!0);var Tc={aa:{value:0,configurable:!0,writable:!0,enumerable:!1}},Uc=Object.defineProperties,D=Kc?Mc:"aa",Vc,Wc=[];E(Wc,7);Vc=Object.freeze(Wc);function Xc(a,b){Kc||D in a||Uc(a,Tc);a[D]|=b}function E(a,b){Kc||D in a||Uc(a,Tc);a[D]=b}function Yc(a){Xc(a,8192);return a};var Zc={};function $c(a,b){return b===void 0?a.g!==ad&&!!(2&(a.j[D]|0)):!!(2&b)&&a.g!==ad}var ad={};function bd(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var cd={};function dd(a){return a&128?cd:void 0};function ed(a){return a};var fd=void 0;function gd(a,b){if(a!=null){var c;var d=(c=fd)!=null?c:fd={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",zb(a))}};function hd(a){return Array.prototype.slice.call(a)};var id=typeof BigInt==="function"?BigInt.asIntN:void 0,nd=typeof BigInt==="function"?BigInt.asUintN:void 0,od=Number.isSafeInteger,pd=Number.isFinite,qd=Math.trunc;function rd(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function sd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function td(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var ud=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function vd(a){switch(typeof a){case "bigint":return!0;case "number":return pd(a);case "string":return ud.test(a);default:return!1}}function wd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return pd(a)?a|0:void 0}
function xd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return pd(a)?a>>>0:void 0}
function yd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(id(64,a));if(vd(a)){if(b==="string")return b=qd(Number(a)),od(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")||(gb(a),a=eb(v,y))),a;if(b==="number")return a=qd(a),od(a)||(Wa(a),a=cb(v,y)),a}}
function zd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(nd(64,a));if(vd(a)){if(b==="string")return b=qd(Number(a)),od(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a[0]==="-"?b=!1:(b=a.length,b=b<20?!0:b===20&&a<="18446744073709551615"),b||(gb(a),a=ab(v,y))),a;if(b==="number")return a=qd(a),a>=0&&od(a)||(Wa(a),a=$a(v,y)),a}}function Ad(a){if(a==null||typeof a=="string"||a instanceof Pb)return a}
function Bd(a){if(a!=null&&typeof a!=="string")throw Error();return a}function Cd(a){return a==null||typeof a==="string"?a:void 0};function Dd(a){var b=Ca(Oc);return b?a[b]:void 0}function Ed(){}function Fd(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function Gd(a){var b=new Ed;Fd(a,function(c,d,e){b[d]=hd(e)});b.g=a.g;return b}function Hd(a,b){b<100||gd(Pc,1)};function Id(a,b,c,d){var e=d!==void 0;d=!!d;var f=Ca(Oc),g;!e&&Kc&&f&&(g=a[f])&&Fd(g,Hd);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var w=h&&a[h-1];w!=null&&typeof w==="object"&&w.constructor===Object?(h--,g=h):w=void 0;if(m&&!(b&128)&&!e){k=!0;var x;g=((x=Jd)!=null?x:ed)(g-n,n,a,w,void 0)+n}}b=void 0;for(x=0;x<h;x++){var z=a[x];if(z!=null&&(z=c(z,d))!=null)if(m&&x>=g){var G=x-n,C=void 0;((C=b)!=null?C:b={})[G]=z}else f[x]=z}if(w)for(var T in w)h=w[T],h!=
null&&(h=c(h,d))!=null&&(x=+T,z=void 0,m&&!Number.isNaN(x)&&(z=x+n)<g?f[z]=h:(x=void 0,((x=b)!=null?x:b={})[T]=h));b&&(k?f.push(b):f[g]=b);e&&Ca(Oc)&&(a=Dd(a))&&a instanceof Ed&&(f[Oc]=Gd(a));return f}
function Kd(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Sa(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[D]|0;return a.length===0&&b&1?void 0:Id(a,b,Kd)}if(a!=null&&a[Sc]===Zc)return Ld(a);if(a instanceof Pb){b=a.g;if(b==null)a="";else if(typeof b==="string")a=b;else{if(Jb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=String.fromCharCode.apply(null,d?b.subarray(d):
b);b=btoa(c)}else{c===void 0&&(c=0);Hb();c=Db[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.g=b}return a}return}return a}var Jd;function Ld(a){a=a.j;return Id(a,a[D]|0,Kd)};var Md,Nd;function Od(a){switch(typeof a){case "boolean":return Md||(Md=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Nd||(Nd=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Pd(a,b){return F(a,b[0],b[1])}
function F(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[D]|0;if(Ea&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Qd();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&E(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-16760833|(g&1023)<<14;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}E(a,e|64|d);return a}function Qd(){if(Ea)throw Error("carr");gd(Rc,5)};function Rd(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[D]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=Sd(a,c,!1,b&&!(c&16)):(Xc(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Sc]===Zc)return b=a.j,c=b[D]|0,$c(a,c)?a:Td(a,b,c)?Ud(a,b):Sd(b,c);if(a instanceof Pb)return a}function Ud(a,b,c){a=new a.constructor(b);c&&(a.g=ad);a.h=ad;return a}function Sd(a,b,c,d){d!=null||(d=!!(34&b));a=Id(a,b,Rd,d);d=32;c&&(d|=2);b=b&16769217|d;E(a,b);return a}
function Vd(a){if(a.g!==ad)return!1;var b=a.j;b=Sd(b,b[D]|0);Xc(b,2048);a.j=b;a.g=void 0;a.h=void 0;return!0}function Wd(a){if(!Vd(a)&&$c(a,a.j[D]|0))throw Error();}function Xd(a,b){b===void 0&&(b=a[D]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Td(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=ad,!0):!1};function Yd(a,b,c){a=Zd(a.j,b,void 0,c);if(a!==null)return a}function Zd(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function $d(a,b,c){Wd(a);var d=a.j;H(d,d[D]|0,b,c);return a}
function H(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[D]|0)>>14&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function ae(a,b){return be(a,a[D]|0,b)}function ce(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function de(a){return a==null?a:typeof a==="string"?a?new Pb(a,Ob):Rb():a.constructor===Pb?a:Ib&&a!=null&&a instanceof Uint8Array?a.length?new Pb(new Uint8Array(a),Ob):Rb():void 0}function be(a,b,c){if(b&2)throw Error();var d=dd(b);var e=Zd(a,c,d);e=Array.isArray(e)?e:Vc;var f=e===Vc?7:e[D]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||ce(g)||16&g)g===f||ce(g)||E(e,g),e=hd(e),f=0,g=ee(g,b),H(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function fe(a,b,c,d){Wd(a);var e=a.j,f=e[D]|0;if(d==null){var g=ge(e);if(he(g,e,f,c)===b)g.set(c,0);else return a}else f=ie(e,f,c,b);H(e,f,b,d);return a}function je(a,b,c,d){var e=a[D]|0,f=dd(e);e=ie(a,e,c,b,f);H(a,e,b,d,f)}function ge(a){if(Kc){var b;return(b=a[Nc])!=null?b:a[Nc]=new Map}if(Nc in a)return a[Nc];b=new Map;Object.defineProperty(a,Nc,{value:b});return b}function ie(a,b,c,d,e){var f=ge(a),g=he(f,a,b,c,e);g!==d&&(g&&(b=H(a,b,g,void 0,e)),f.set(c,d));return b}
function he(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];Zd(b,h,e)!=null&&(f!==0&&(c=H(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function ke(a,b,c){var d=a[D]|0,e=dd(d),f=Zd(a,c,e);if(f!=null&&f[Sc]===Zc){if(!$c(f))return Vd(f),f.j;var g=f.j}else Array.isArray(f)&&(g=f);if(g){var h=g[D]|0;h&2&&(g=Sd(g,h))}g=Pd(g,b);g!==f&&H(a,d,c,g,e);return g}
function le(a,b){var c=me,d=!1,e=Zd(a,4,void 0,function(f){if(f!=null&&f[Sc]===Zc)var g=f;else if(Array.isArray(f)){g=f[D]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!$c(e)&&Xd(a,b),e}function ne(a){var b=a.j,c=b[D]|0,d=le(b,c);if(d==null)return d;c=b[D]|0;if(!$c(a,c)){var e=d;var f=e.j,g=f[D]|0;e=$c(e,g)?Td(e,f,g)?Ud(e,f,!0):new e.constructor(Sd(f,g,!1)):e;e!==d&&(Vd(a)&&(b=a.j,c=b[D]|0),d=e,c=H(b,c,4,d),Xd(b,c))}return d}
function oe(a){a==null&&(a=void 0);return a}function pe(a,b,c){c=oe(c);$d(a,b,c);c&&!$c(c)&&Xd(a.j);return a}function qe(a,b){Wd(a);var c=a.j,d=c[D]|0;if(b==null)return H(c,d,1),a;for(var e=b===Vc?7:b[D]|0,f=e,g=ce(e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var w=b[n];g||(w=$c(w),k&&(k=!w),m&&(m=w))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=hd(b),f=0,e=ee(e,d));e!==f&&E(b,e);d=H(c,d,1,b);2&e||!(4096&e||16&e)||Xd(c,d);return a}function ee(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.j=F(a,b,c,2048)}I.prototype.toJSON=function(){var a=Ld(this);return a};I.prototype[Sc]=Zc;I.prototype.toString=function(){return this.j.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var re=J(),se=J(),te=J(),ue=J(),ve=J(),we=J(),xe=J(),ye=J(),ze=J(),Ae=J();function Be(a,b,c){this.g=a;this.h=b;a=Ca(re);this.i=!!a&&c===a||!1}function Ce(a,b){var c=c===void 0?re:c;return new Be(a,b,c)}function De(a,b,c,d,e){Ic(a,c,Ee(b,d),e)}var Fe=Ce(function(a,b,c,d,e){if(a.g!==2)return!1;yc(a,ke(b,d,c),e);return!0},De),Ge=Ce(function(a,b,c,d,e){if(a.g!==2)return!1;yc(a,ke(b,d,c),e);return!0},De),He=Symbol(),Ie=Symbol(),Je=Symbol(),Ke=Symbol(),Le=Symbol(),Me,Ne;
function Oe(a,b,c,d){var e=d[a];if(e)return e;e={};e.Z=d;e.I=Od(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.U=f,f=d[++g],typeof f==="function"&&(e.X=!0,Me!=null||(Me=f),Ne!=null||(Ne=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof Be)var n=f;else n=Fe,g--;f=void 0;if((f=n)==null?0:f.i){f=d[++g];m=d;var w=g;typeof f===
"function"&&(f=f(),m[w]=f);m=f}f=d[++g];w=k+1;typeof f==="number"&&f<0&&(w-=f,f=d[++g]);for(;k<w;k++){var x=h[k];m?c(e,k,n,m,x):b(e,k,n,x)}}return d[a]=e}function Pe(a){return Array.isArray(a)?a[0]instanceof Be?a:[Ge,a]:[a,void 0]}function Ee(a,b){if(a instanceof I)return a.j;if(Array.isArray(a))return Pd(a,b)};function Qe(a,b,c,d){var e=c.g;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Re(a,b,c,d,e){var f=c.g,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=Oe(Ie,Qe,Re,d).I),g||(g=Se(d)),e)}}
function Se(a){var b=a[Je];if(b!=null)return b;var c=Oe(Ie,Qe,Re,a);b=c.X?function(d,e){return Me(d,e,c)}:function(d,e){for(;wc(e)&&e.g!=4;){var f=e.i,g=c[f];if(g==null){var h=c.U;h&&(h=h[f])&&(h=Te(h),h!=null&&(g=c[f]=h))}if(g==null||!g(e,d,f)){h=e;g=h.l;xc(h);if(h.T)var k=void 0;else{var m=h.h.g-g;h.h.g=g;k=lc(h.h,m)}m=h=g=void 0;var n=d;k&&((g=(h=(m=n[Oc])!=null?m:n[Oc]=new Ed)[f])!=null?g:h[f]=[]).push(k)}}if(d=Dd(d))d.g=c.Z[Le];return!0};a[Je]=b;a[Le]=Ue.bind(a);return b}
function Ue(a,b,c,d){var e=this[Ie],f=this[Je],g=Pd(void 0,e.I),h=Dd(a);if(h){var k=!1,m=e.U;if(m){e=function(G,C,T){if(T.length!==0)if(m[C])for(G=q(T),C=G.next();!C.done;C=G.next()){C=tc(C.value);try{k=!0,f(g,C)}finally{vc(C)}}else d==null||d(a,C,T)};if(b==null)Fd(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var w=a[D]|0;if(w&2&&w&2048&&(c==null||!c.ea))throw Error();var x=dd(w),z=function(G,C){if(Zd(a,G,x)!=null)switch(c==null?void 0:c.da){case 1:return;default:throw Error();}C!=null&&(w=
H(a,w,G,C,x));delete h[G]};b==null?bd(g,g[D]|0,function(G,C){z(G,C)}):z(b,Zd(g,b,x))}}}}function Te(a){a=Pe(a);var b=a[0].g;if(a=a[1]){var c=Se(a),d=Oe(Ie,Qe,Re,a).I;return function(e,f,g){return b(e,f,g,d,c)}}return b};function Ve(a,b,c){a[b]=c.h}function We(a,b,c,d){var e,f,g=c.h;a[b]=function(h,k,m){return g(h,k,m,f||(f=Oe(He,Ve,We,d).I),e||(e=Xe(d)))}}function Xe(a){var b=a[Ke];if(!b){var c=Oe(He,Ve,We,a);b=function(d,e){return Ye(d,e,c)};a[Ke]=b}return b}function Ye(a,b,c){bd(a,a[D]|0,function(d,e){if(e!=null){var f=Ze(c,d);f?f(b,e,d):d<500||gd(Qc,3)}});(a=Dd(a))&&Fd(a,function(d,e,f){Dc(b,b.g.end());for(d=0;d<f.length;d++)Dc(b,Tb(f[d])||new Uint8Array(0))})}
function Ze(a,b){var c=a[b];if(c)return c;if(c=a.U)if(c=c[b]){c=Pe(c);var d=c[0].h;if(c=c[1]){var e=Xe(c),f=Oe(He,Ve,We,c).I;c=a.X?Ne(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[D]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);a=d|1;c&&(a=(a|4)&-1537);a!==d&&E(b,a);c&&a&2&&Object.freeze(b);return b}}function L(a,b,c){return new Be(a,b,c)}function M(a,b,c){return new Be(a,b,c)}function N(a,b,c){H(a,a[D]|0,b,c,dd(a[D]|0))}
var $e=Ce(function(a,b,c,d,e){if(a.g!==2)return!1;a=yc(a,Pd([void 0,void 0],d),e);a=hd(a);d=b[D]|0;e=dd(d);if(d&2)throw Error();var f=Zd(b,c,e);if(Array.isArray(f)){var g=f[D]|0;g&8192||E(f,g|=8192);if(g&2){f=hd(f);for(g=0;g<f.length;g++){var h=f[g]=hd(f[g]);if(Array.isArray(h[1])){var k=h[1];Xc(k,34);h[1]=k}}f=Yc(f);H(b,d,c,f,e)}f.push(a)}else H(b,d,c,Yc([a]),e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&Ic(a,c,Pd(g,d),e)}Yc(b)}});
function af(a,b,c){b=sd(b);b!=null&&(B(a,c,1),a=a.g,Za(b),A(a,v),A(a,y))}function bf(a,b,c){b=sd(b);b!=null&&(B(a,c,5),a=a.g,Ya(b),A(a,v))}function cf(a,b,c){b=yd(b);if(b!=null){switch(typeof b){case "string":ob(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Wa(b);pc(a,v,y);break;case "bigint":c=nb(b);pc(a.g,c.h,c.g);break;default:c=ob(b),pc(a.g,c.h,c.g)}}}
function df(a,b,c){b=zd(b);if(b!=null){switch(typeof b){case "string":kb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Wa(b);pc(a,v,y);break;case "bigint":c=jb(b);pc(a.g,c.h,c.g);break;default:c=kb(b),pc(a.g,c.h,c.g)}}}function ef(a,b,c){b=wd(b);b!=null&&b!=null&&(B(a,c,0),rc(a.g,b))}function ff(a,b,c){b=td(b);b!=null&&(B(a,c,0),a.g.g.push(b?1:0))}function gf(a,b,c){b=Cd(b);b!=null&&Hc(a,c,yb(b))}function hf(a,b,c,d,e){Ic(a,c,Ee(b,d),e)}function jf(a,b,c){Gc(a,c,wd(b))}
function kf(a,b,c){if(a.g!==5&&a.g!==2)return!1;b=ae(b,c);a.g==2?Bc(a,fc,b):b.push(fc(a.h));return!0}function lf(a,b,c){if(a.g!==0)return!1;N(b,c,Yb(a.h,bb));return!0}function mf(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=ae(b,c);a.g==2?Bc(a,$b,b):b.push($b(a.h));return!0}function nf(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=ae(b,c);a.g==2?Bc(a,ic,b):b.push(ic(a.h));return!0}
var of=L(function(a,b,c){if(a.g!==1)return!1;N(b,c,hc(a.h));return!0},af,ye),pf=L(function(a,b,c,d){if(a.g!==1)return!1;je(b,c,d,hc(a.h));return!0},af,ye),O=L(function(a,b,c){if(a.g!==5)return!1;N(b,c,fc(a.h));return!0},bf,xe),qf=M(kf,function(a,b,c){b=K(sd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.g,Ya(g),A(e,v))}},xe),P=M(kf,function(a,b,c){b=K(sd,b,!0);if(b!=null&&b.length)for(B(a,c,2),qc(a.g,b.length*4),c=0;c<b.length;c++){var d=a.g;Ya(b[c]);A(d,v)}},
xe),rf=L(function(a,b,c,d){if(a.g!==5)return!1;je(b,c,d,fc(a.h));return!0},bf,xe),sf=L(function(a,b,c){if(Fa)return a.g!==0?a=!1:(N(b,c,dc(a.h)),a=!0),a;if(a.g!==0)return!1;N(b,c,cc(a.h));return!0},cf,ve),tf=M(function(a,b,c){if(Fa)return a.g!==0&&a.g!==2?a=!1:(b=ae(b,c),a.g==2?Bc(a,dc,b):b.push(dc(a.h)),a=!0),a;if(a.g!==0&&a.g!==2)return!1;b=ae(b,c);a.g==2?Bc(a,cc,b):b.push(cc(a.h));return!0},function(a,b,c){b=K(yd,b,!1);if(b!=null&&b.length){c=Ec(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=
a.g;Wa(e);pc(f,v,y);break;case "bigint":e=nb(e);pc(a.g,e.h,e.g);break;default:e=ob(e),pc(a.g,e.h,e.g)}}Fc(a,c)}},ve),uf=L(function(a,b,c,d){if(Fa)return a.g!==0?a=!1:(je(b,c,d,dc(a.h)),a=!0),a;if(a.g!==0)return!1;je(b,c,d,cc(a.h));return!0},cf,ve),vf=L(function(a,b,c){if(Fa)return lf(a,b,c);if(a.g!==0)return!1;N(b,c,Yb(a.h,ab));return!0},df,we),wf=L(function(a,b,c){if(Fa)return lf(a,b,c);if(a.g!==0)return!1;N(b,c,Yb(a.h,$a));return!0},df,we),Q=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,$b(a.h));
return!0},ef,ue),xf=M(mf,function(a,b,c){b=K(wd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),rc(e.g,g))}},ue),yf=M(mf,function(a,b,c){b=K(wd,b,!0);if(b!=null&&b.length){c=Ec(a,c);for(var d=0;d<b.length;d++)rc(a.g,b[d]);Fc(a,c)}},ue),zf=L(function(a,b,c,d){if(a.g!==0)return!1;je(b,c,d,$b(a.h));return!0},ef,ue),R=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,ic(a.h));return!0},ff,se),Af=M(nf,function(a,b,c){b=K(td,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,0),e.g.g.push(g?1:0))}},se),Bf=M(nf,function(a,b,c){b=K(td,b,!0);if(b!=null&&b.length)for(B(a,c,2),qc(a.g,b.length),c=0;c<b.length;c++)a.g.g.push(b[c]?1:0)},se),Cf=L(function(a,b,c,d){if(a.g!==0)return!1;je(b,c,d,ic(a.h));return!0},ff,se),S=L(function(a,b,c){if(a.g!==2)return!1;N(b,c,zc(a));return!0},gf,te),Df=L(function(a,b,c,d){if(a.g!==2)return!1;je(b,c,d,zc(a));return!0},gf,te),U=M(function(a,b,c){if(a.g!==2)return!1;a=zc(a);be(b,b[D]|0,c).push(a);return!0},function(a,
b,c){b=K(Cd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Hc(e,f,yb(g))}},te),V,Ef=void 0;Ef=Ef===void 0?re:Ef;V=new Be(function(a,b,c,d,e){if(a.g!==2)return!1;d=Pd(void 0,d);be(b,b[D]|0,c).push(d);yc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)hf(a,b[f],c,d,e);a=b[D]|0;a&1||E(b,a|1)}},Ef);
var W=Ce(function(a,b,c,d,e,f){if(a.g!==2)return!1;var g=b[D]|0;ie(b,g,f,c,dd(g));b=ke(b,d,c);yc(a,b,e);return!0},hf),Ff=L(function(a,b,c){if(a.g!==2)return!1;N(b,c,Ac(a));return!0},function(a,b,c){b=Ad(b);b!=null&&Hc(a,c,Wb(b,!0).buffer)},ze),X=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,ac(a.h));return!0},function(a,b,c){b=xd(b);b!=null&&b!=null&&(B(a,c,0),qc(a.g,b))},J()),Y=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,$b(a.h));return!0},jf,Ae),Gf=M(function(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=
ae(b,c);a.g==2?Bc(a,jc,b):b.push($b(a.h));return!0},function(a,b,c){b=K(wd,b,!0);if(b!=null)for(var d=0;d<b.length;d++)Gc(a,c,b[d])},Ae),Hf=L(function(a,b,c,d){if(a.g!==0)return!1;je(b,c,d,$b(a.h));return!0},jf,Ae),If=M(function(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=ae(b,c);a.g==2?Bc(a,bc,b):b.push(bc(a.h));return!0},function(a,b,c){b=K(wd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),qc(e.g,(g<<1^g>>31)>>>0))}},J()),Jf=[!0,S,Q],Kf=[!0,S,R],Lf=[!0,S,S];function Mf(a){return function(b){var c=new Cc;Ye(b.j,c,Oe(He,Ve,We,a));Dc(c,c.g.end());b=new Uint8Array(c.h);for(var d=c.i,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.i=[b];return b}};var Nf=[0,L(function(a,b,c){if(Fa){if(a.g!==1)b=!1;else{var d=a.h;a=ec(d);d=ec(d);N(b,c,bb(a,d));b=!0}return b}if(a.g!==1)return!1;d=a.h;a=ec(d);d=ec(d);N(b,c,ab(a,d));return!0},function(a,b,c){b=zd(b);if(b!=null)switch(Jc(b),B(a,c,1),a=a.g,Jc(b),typeof b){case "number":b<0?(c=-b,c=ib(new hb(c&4294967295,c/4294967296)),b=c.g,A(a,c.h),A(a,b)):(Va(b),A(a,v),A(a,y));break;case "bigint":c=b<BigInt(0)?ib(jb(-b)):jb(b);b=c.g;A(a,c.h);A(a,b);break;default:c=b.length&&b[0]==="-"?ib(kb(b.substring(1))):kb(b),
b=c.g,A(a,c.h),A(a,b)}},J()),-1];var Of=[0,L(function(a,b,c){if(a.g!==5)return!1;a=a.h;var d=a.h,e=a.g,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];Zb(a,a.g+4);N(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=wd(b);b!=null&&(B(a,c,5),a=a.g,a.g.push(b>>>0&255),a.g.push(b>>>8&255),a.g.push(b>>>16&255),a.g.push(b>>>24&255))},J()),-1];var Pf=[0,Y,-1,sf,S,Of,-1,O,Q,Y,Nf,S,Y,-1,[0,Of,-1],Q,wf,Nf,O,[0,1,Q,-4,of,[0,O,-1,Q],S,O,V,[0,Y,Q],Q,-1,Y,-2,O,-1,Y,O,Y,Q,[0,3,Q,-1,4,M(function(a,b,c){if(a.g!==2)return!1;a=Ac(a);be(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(Ad,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Hc(e,f,Wb(g,!0).buffer)}},ze)],of,X],S,Gf,V,[0,Nf,V,[0,S,Y],O,Y,-1],1,V,[0,wf,-1,X],Y,Nf];var Qf=[0,sf,[0,O,S,Q,S,Q,xf,sf,S,Q,S,-1,O,Q,O],Ff,[0,M(function(a,b,c){if(a.g!==1&&a.g!==2)return!1;b=ae(b,c);if(a.g==2){c=a.h;a=ac(a.h)/8;var d=c.g,e=8*a;if(d+e>c.i)throw Error();var f=c.h;d+=f.byteOffset;nc===void 0&&(nc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(nc)for(c.g+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(hc(c))}else b.push(hc(a.h));return!0},function(a,b,c){b=K(sd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.g,Za(g),A(e,v),A(e,y))}},ye),-1]];function me(a){this.j=F(a,void 0,void 0,2048)}p(me,I);function Rf(a){a=Yd(a,1,de);return a==null?Rb():a}function Sf(a){var b=16E3;b=b===void 0?0:b;a=wd(Yd(a,2));return a!=null?a:b};function Tf(a){this.j=F(a,void 0,void 0,2048)}p(Tf,I);function Uf(a){this.j=F(a,void 0,void 0,2048)}p(Uf,I);var Vf=[0,Ff,Q];var Wf=[0,[1,2,3,4],Df,Hf,W,[0,S,Y],Hf];var Xf=[0,S,-2,3,O,S,U,Y,-1,V,Wf,S,-2];var Yf=[0,Q,-3];var Zf=[0,[1,2,3,4],Cf,-1,Df,-1];var bg=[0,S,-1,1,S,-1,6,U,[0,X,S,X,Q,X,-4,O,X,O,-1],R,U,-1];var Z=[0,Y,-5];var cg=[0,[0,S,-5,R,U,Z],S,-7,R,S,U,Z];var dg=[0,U,1,Y,-1,S];var eg=[0,S,-2,Z,S];var fg=[0,S,-1,R,S,U,Z];var gg=[0,V,[0,S,-1],S,R,S];var hg=[0,S,-2,Z];var ig=[0,S,-3,Q,S,R,S,-1,R,S,U,Z,S,-2];var jg=[0,R,S,-3,Q,S,R,S,U,Z];var kg=[0,S,-3,Q,S,-3,R,S,U,Z];var lg=[0,S,Q,Y,S];var mg=[0,S,-2,Q,S,R,S,R,U,Z];var ng=[0,S,-2,R];var og=[0,jg,mg,fg,S,Q,S,R,S,U,Z];var pg=[0,jg,sf,S,Q,S,R,S,U,Z,S];var qg=[0,S,-1,R,S,U,Z,R];var rg=[0,S,Q,R];var sg=[0,S,U,S,Q,S,R,S,U,Z];var tg=[0,Q,-2,R,S,Q,S,Q,S,R,S,U,Z,R];var ug=[0,Y,-1];var vg=[0,O,-1];var wg=[0,V,[0,O,-2],O,-1,Q,V,[0,Q,Y,Q,Y,X,Y,-1,V,vg,[0,O,-1],[0,V,vg,O,Y],[0,V,vg,Y]],O];var xg=[0,O,-2];var yg=[-11,{},Yf,S,[0,Bf,yf,P,U,V,[0,P],[0,P]],P,S,-1,[0,xg],S,[0,P,-1,V,[0,Y,Q]],-1];var zg=[0,Yf,[0,R,O,P,-1],Q,[0,P]];var Ag=[0,Q,-2];var Bg=[0,Y,[0,xf,tf]];var Cg=[0,Y,[0,xf,U]];var Dg=[0,Q,-1,Y,Q];var Eg=[0,P,yf];var Fg=[0,P,yf,S];var Gg=[0,[0,vf,Y,R]];var Hg=[0,Q,-2,S];var Ig=[0,Y];var Kg=[-15,{},V,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],Df,S,W,fg,W,qg,W,jg,W,mg,W,tg,W,og,W,ig,W,cg,W,sg,W,pg,W,kg,W,gg,Df,-1,V,ng,Df,-1,wg,rf,[0,R,-1,Y,ug,R,-1,O,R,U,Dg,Y,-1],Pf,R,W,[0,S,-1],V,[0,S,-1],[0,U,R],Z,Y,Ig,R,W,rg,S,U,S,W,hg,W,eg,S,-1,R,W,lg,R,Hg,S],V,[0,S,V,[0,S,-1,Y],V,[0,S,-1],S,Y,[0,Y,-3],U,R,S],4,Ig,O,R,function(){return Jg},S,Gg,R,[0,R,-1]],Jg=[0,V,function(){return Kg},-1];var Lg=function(a,b){return function(c,d){var e={L:!0};d&&Object.assign(e,d);c=tc(c,void 0,void 0,e);try{var f=new a,g=f.j;Se(b)(g,c);var h=f}finally{vc(c)}return h}}(Uf,[0,Y,2,Vf,Y,[-500,{},wf,S,Kg,-1,1,[0,Y,Q,-1,O],[0,S,-5,Q,S,1,R,-1,S,Y,V,Xf,S],sf,-2,89,[-5,{},V,[-75,{},Yf,X,-1,S,Y,S,-2,R,O,Y,S,R,-1,5,fg,qg,S,jg,mg,tg,og,jg,ig,cg,sg,pg,kg,S,-1,hg,S,eg,1,gg,lg,[0,S,-1],V,ng,7,bg,1,S,R,S,R,rg,S,R,S,-2,Zf,S,R,O,U,1,S,R,1,S,dg,Y,R],V,[-71,{},Yf,Y,S,-1,R,1,S,Y,bg,O,Y,R,Gf,S,ug,1,Q,R,1,S,Y,O,[0,[0,O,
-2],[0,O,-2]],[0,Y,-2],25,wg,S,3,R,-1,1,R,S,2,R,Zf,S,Y,O,S,-1,1,S],V,[-11,{},Yf,S,Y,5,[0,Q,-3],S],V,[-12,{},Yf,S,R,O,-1,[0,O,-6,V,[0,S,Y,O]],qf,Q,-1,S,[0,[0,Q,-3],V,[0,S,O]]]],1,[0,3,V,[0,V,Ag,Ag],R],3,Dg,Y,-1,1,[-12,{},Dg,Y,-1,[0,Y,2,Y,-1],Y,-1,S,3,[0,R,-2]],39,[0,[0,Q,-2,yf,-2],Cg,-2,Bg,Cg,-2,Bg,-5],49,[-3,{},[0,V,yg,[0,V,[0,S,V,[0,Q,O,V,[0,Q,O,-1,Q],R],V,[0,Q,O],R,-2]]],V,[0,Q,V,[0,Yf,[-10,{},Q,-2,X,[0,X,-2,O,-8,qf,-5,If,-1],Gf,Q,-2],xg,O,-2,V,[0,Y,qf]]]],[-3,{},[0,V,yg],V,[-6,{},V,zg,V,xg,xf,
Af,yf]],48,[0,[0,V,zg,Qf],[0,O,X,-1,O,X]],49,Vf,599,[-1,{}],R,[0,O,-2,Q],[-3,{},V,[-7,{},X,-1,R,V,[0,[1,2,3,4],W,[-5,{},Y,S,-1,R],W,[0],W,[0],W,[0]],O,X],X],Eg,V,Fg]]);var Mg=Mf(Xf);function Ng(a){this.j=F(a,void 0,void 0,2048)}p(Ng,I);var Og=[1,4];function Pg(a){this.j=F(a,11,void 0,2048)}p(Pg,I);var Qg=[0,Q,Ff,Y];var Rg=[-11,{},[0,V,[0,Y,1,Y],Gf,Pf,U,V,[0,S,Y,O,Y],1,Y,-1,R],[0,S,-3,O,[0,Q,S],Gf,-1],[0,Og,rf,[0,Y],[0,2,Y],Hf,[0,R,-1],O,Y,-2],[0,1,O,V,[0,S,-1],Gf,Gg,Q],dg,[-1,{}],[0,[1,3],W,[0,[3,4],V,Wf,-1,zf,Cf,V,Wf],S,Df],[0,[1,2,3,4,5,6,7,8,9,10,11],Hf,-10],[0,[1,2],[6],[3,4,5],W,Qg,W,Eg,W,Qg,W,Eg,W,[0,P],W,[0,Q,-1,R]],[0,[1],W,Eg,V,Fg,Qg]];var Sg=[-3,{},S,Rg];function Tg(a){this.j=F(a,void 0,void 0,2048)}p(Tg,I);function Ug(a){this.j=F(a,5,void 0,2048)}p(Ug,I);function Vg(a){this.j=F(a,void 0,void 0,2048)}p(Vg,I);var Wg=[2,3,4];var Xg=[0,S,-2];var Yg=[0,[3,4],S,-1,uf,pf,Q,-1,S,-1];var Zg=[0,Wg,Q,W,[-5,{},V,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],Q,S,-1,Rg,V,[0,[4,5],Q,S,-1,Hf,Df,S,Rg,Y],S,-1,Hg,R,90,Df,W,[0,S,Y,[0,Y,O,Y]],W,[0,S],W,[0,S,Q],W,[0,S,Y],W,[0,S,-1],W,[0,S,Y],W,Yg,W,[0,1,S],W,Xg,W,[0,U,Y],W,[0,[5,6,7],Q,-2,S,Hf,-1,zf],W,[0,[5,6],Q,-3,Hf,zf],W,[0,[1,2],[4,5,6],W,Yg,W,Xg,S,Hf,-1,zf],W,[0,[3,4],[8,9,10],Q,-1,zf,Df,Q,Y,S,Hf,-1,zf],W,[0,S,U,S],W,[0,[4,5,6],Yg,S,1,Hf,-1,zf],W,[0,S,-3,Q,S,-2],W,[0,S,Y],W,[0,V,[0,S,-1],S,
R],W,[0,S,-1]],Rg,V,[0,Q,-1,Rg],R],W,Sg,W,[0,[1,2],W,Qg,W,[0,S]]];var $g=[0,$e,Kf,$e,Jf,$e,Lf];function ah(a){this.j=F(a,4,void 0,2048)}p(ah,I);var bh=[-4,{},V,Zg,Rg,$g];function ch(a){this.j=F(a,3,void 0,2048)}p(ch,I);var dh=Mf([-3,{},V,Kg,bh]);function eh(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.h=!1;this.o=[];this.S={};this.P={};this.C={};this.R={};this.B={};this.Y=new TextEncoder;this.V="";this.H=null;this.M=0;this.N=[];this.G=this.u=this.D=this.l=!1;this.v=[];this.O=[];this.A=[];this.i=a;this.F=this.i.createGain()}aa=eh.prototype;
aa.init=function(a){var b=this;return t(function(c){switch(c.g){case 1:if(b.h)return c.return();b.h=!0;b.extensionId=a;return r(c,loadWasmTtsBindings(),2);case 2:return b.g=c.h,r(c,fh(b),3);case 3:return r(c,gh(b),4);case 4:return c.return(hh(b))}})};aa.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?(b.h?(e.g=2,e=void 0):e=r(e,b.init(b.extensionId),2),e):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,r(e,ih(b,a),4)):e.return({type:c,lang:d,status:e.h})})};
aa.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?(b.h?(e.g=2,e=void 0):e=r(e,b.init(b.extensionId),2),e):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,r(e,jh(b,a),4)):e.return({type:c,lang:d,status:e.h})})};
aa.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.g==1)return b.h?(d.g=2,d=void 0):d=r(d,b.init(b.extensionId),2),d;if(d.g!=4)return r(d,kh(b,a),4);(c=d.h)&&lh(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function kh(a,b){var c,d,e,f,g,h;return t(function(k){switch(k.g){case 1:c=mh(a,b),d=!1,e=q(c),f=e.next();case 2:if(f.done){k.g=4;break}g=f.value;nh(a,g);if(!g.remote||g.unloaded){k.g=3;break}h="/voices/"+g.fileId;k.i=5;return r(k,oh(a,h),7);case 7:d=!0;pa(k,3);break;case 5:qa(k);case 3:f=e.next();k.g=2;break;case 4:return k.return(d)}})}
aa.onStop=function(a){var b=this,c;return t(function(d){if(!b.h)return d.return();ph(b);b.l=!1;b.D=!1;b.u=a;b.m&&(c={command:"clearBuffers"},b.m.port.postMessage(c),b.m.disconnect());for(qh(b);b.O.length>0;)window.clearTimeout(b.O.pop());b.v=[];b.N.length=0;b.H=null;b.M=0;d.g=0})};aa.onPause=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h)return b.return();qh(a);a.u=!0;return r(b,a.i.suspend(),2)}a.l=!1;b.g=0})};
aa.onResume=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h||a.l)return b.return();a.u=!1;return a.D?r(b,a.i.resume(),2):(a.A.length===0&&rh(a),b.return(sh(a)))}a.l=!0;th(a);b.g=0})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.g){case 1:return c.u=!1,r(k,c.init(c.extensionId),2);case 2:if(!c.g)throw Error("WASM module not initialized.");return b.voiceName?r(k,c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.V===d){k.g=4;break}k.i=5;return r(k,uh(c,d,!1),7);case 7:e=c.C[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.g){var m=vh(c,g);var n=vh(c,f),w=c.g._GoogleTtsInit(m,
n);c.g._free(n);c.g._free(m);m=w===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);pa(k,4);break;case 5:return qa(k),k.return(Promise.reject(Error("Voice is not available")));case 4:c.V=d;var x=b.lang;c.extensionId&&x&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:x});try{if(x=d,c.g&&a.length){var z=new Ug,G=new Tg;var C=$d(G,2,Bd(a));var T=qe(z,[C]);var Ch=new Ng,Ub=b.rate;var Dh=fe(Ch,1,Og,rd(!Ub||Ub<.1||Ub>10?1:Ub));var $f=b.pitch;m=$d(Dh,6,rd($f?Math.pow(2,
($f-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.F.gain.value=Math.min(Math.max(b.volume,0),1));n=new ah;w=new Vg;z=T;z=oe(z);fe(w,2,Wg,z);z&&!$c(z)&&Xd(w.j);var Eh=qe(n,[w]);var Fh=new Pg;var Gh=pe(Fh,3,m);var Hh=pe(Eh,2,Gh);var Ih=new ch;var Jh=pe(Ih,2,Hh);var jd=Array.from(new Uint8Array(dh(Jh))),Kh=c.R[x],Lh=new Tf;var Mh=$d(Lh,1,Bd(Kh));var kd=Mg(Mh),ld=c.g._malloc(jd.length);c.g.HEAPU8.set(jd,ld);var md=c.g._malloc(kd.length);c.g.HEAPU8.set(kd,md);var Nh=c.g._GoogleTtsInitBuffered(ld,md,
jd.length,kd.length);c.g._free(ld);c.g._free(md);if(!Nh)throw Error("Failed to initialize buffered synthesis.");rh(c)}}catch(ag){return h=ag instanceof Error?ag.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.g=0}})};
function hh(a){return a.i.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.m=new AudioWorkletNode(a.i,"streaming-worklet-processor");a.m.port.onmessage=function(b){a.utterance&&!a.G&&b.data.type==="empty"&&(wh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.F.connect(a.i.destination)})}function vh(a,b){b=a.Y.encode(b+"\x00");var c=a.g._malloc(b.length);a.g.HEAPU8.set(b,c);return c}
function rh(a){var b=setTimeout(function(){a.G=!0;var c=a.g,d=c._GoogleTtsReadBuffered();if(d===-1)wh(a,{type:"error"}),ph(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)xh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=Lg(c.slice(0,
e));d=d===0;e=c.j;le(e,e[D]|0)!==void 0?yh(a,c,d):zh(a,null);d?ph(a):rh(a)}},0);a.A.push(b)}function ph(a){a.G=!1;a.g._GoogleTtsFinalizeBuffered()}function qh(a){for(;a.A.length>0;)window.clearTimeout(a.A.pop())}function xh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.l?c<-100||(c<2?wh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.l?wh(a,{type:"word",charIndex:d,length:e}):a.v.push(b)},c),a.O.push(c))):a.v.push(b))}
function th(a){var b=a.v;a.v=[];b=q(b);for(var c=b.next();!c.done;c=b.next())xh(a,c.value)}function yh(a,b,c){if(Sf(ne(b))===24E3){var d;b=(d=Rf(ne(b)))==null?void 0:new Uint8Array(Tb(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});Ah(a,d,c)}}
function Ah(a,b,c){for(var d=a.H,e=a.M,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(zh(a,d),e=0,d=null)}e!==0&&(c?zh(a,d):(a.H=d,a.M=e))}function zh(a,b){b&&a.N.push(b);if(a.m)for(;b=a.N.shift();)a.m.port.postMessage({command:"addBuffer",buffer:b}),a.D||a.u||sh(a)}function sh(a){return t(function(b){if(b.g==1)return a.m.connect(a.F),r(b,a.i.resume(),2);a.l=!0;a.D=!0;wh(a,{type:"start",charIndex:0});th(a);b.g=0})}
function ih(a,b){return t(function(c){return c.return(Bh(a,b,!1))})}function jh(a,b){return t(function(c){return c.return(Bh(a,b,!0))})}function Bh(a,b,c){var d,e,f;return t(function(g){switch(g.g){case 1:return d=mh(a,b),e=d.map(function(h){return uh(a,h.speakers[0].name,c)}),g.i=2,r(g,Promise.all(e),4);case 4:f="installed";c&&lh(a);pa(g,3);break;case 2:qa(g),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function mh(a,b){var c=b.toLowerCase();return c.includes("-")?a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Oh(a,b,c){var d,e,f,g,h,k,m,n,w,x;return t(function(z){if(!a.B[b])return z.return(Promise.resolve());d=a.B[b];f=q(Object.entries(a.P));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,w=m,x=n,d===x){e=w;break}return e?z.return(uh(a,e,c)):z.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function uh(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.g){case 1:if(!a.g)return m.return(Promise.reject(Error("WASM module not initialized.")));m.i=2;return r(m,Oh(a,b,c),4);case 4:pa(m,3);break;case 2:return d=qa(m),m.return(Promise.reject(Error(""+d)));case 3:e=a.C[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.g.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=a.S[b];return c||k.indexOf("http")!==
0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));if(!Ph(a,e,n))return Promise.reject(Error("Failed to validate voice data: "+e));try{a.g.FS.stat(f)}catch(G){a.g.FS.mkdir(f)}a.g.FS.stat(f);var w=vh(a,f),x=new Uint8Array(n),z=a.g._malloc(x.length);a.g.HEAPU8.set(x,z);n=a.g._GoogleTtsInstallVoice(w,z,n.byteLength);a.g._free(w);a.g._free(z);
return n!==1?Promise.reject(Error("Failed to install voice.")):new Promise(function(G,C){a.g.FS.syncfs(!1,function(T){T?C(T):G()})})})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function wh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function fh(a){var b,c;return t(function(d){if(d.g==1){if((b=a.g)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.g.FS.stat("/voices")}catch(e){a.g.FS.mkdir("/voices")}d.i=2;return r(d,new Promise(function(e,f){a.g.FS.mount(a.g.IDBFS,{},"/voices");a.g.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.g!=2)return pa(d,0);c=qa(d);throw c;})}
function gh(a){var b,c,d;return t(function(e){switch(e.g){case 1:return e.i=2,r(e,fetch("voices.json"),4);case 4:b=e.h;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return r(e,b.json(),5);case 5:c=e.h;a.o=c;lh(a);pa(e,0);break;case 2:throw d=qa(e),d;}})}
function lh(a){a.S={};a.P={};a.C={};a.R={};a.B={};for(var b={},c=q(a.o),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.P[f.name]=d.id;a.C[f.name]=d.fileId;a.R[f.name]=f.speaker;d.dependentVoiceId&&(a.B[f.name]=d.dependentVoiceId);nh(a,d);a.S[f.name]=d.remote&&d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||
(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function nh(a,b){try{a.g.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function oh(a,b){if(a.g)try{for(var c=a.g.FS.readdir(b),d=q(c),e=d.next();!e.done;e=d.next()){var f=e.value;f!=="."&&f!==".."&&a.g.FS.unlink(b+"/"+f)}a.g.FS.rmdir(b);return new Promise(function(g,h){a.g.FS.syncfs(!1,function(k){k?h(k):g()})})}catch(g){return Promise.resolve()}}function Ph(a,b,c){var d,e;return t(function(f){if(f.g==1)return r(f,Qh(c),2);d=f.h;e=a.o.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Qh(a){var b,c,d,e;return t(function(f){if(f.g==1)return crypto&&crypto.subtle?r(f,crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.h;c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})}ea.Object.defineProperties(eh.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.o}}});var Rh=new eh,Sh=null;
chrome.runtime.onMessage.addListener(function(a,b,c){Sh||(Sh=Rh.init(b.id));Sh.then(function(){switch(a.type){case "init":Rh.init(b.id);c({result:"Initialized"});break;case "getLanguageStatus":Rh.onLanguageStatusRequest(a.lang).then(c);break;case "installLanguage":Rh.onInstallLanguageRequest(a.lang).then(c);break;case "uninstallLanguage":Rh.onUninstallLanguageRequest(a.lang).then(c);break;case "removeUnusedLanguage":kh(Rh,a.lang).then(function(){c({result:"Removed "+a.lang})});break;case "speak":Rh.onSpeak(a.utterance,
a.options);c({result:"Start speaking"});break;case "stop":Rh.onStop(!0);c({result:"Stopped speech"});break;case "pause":Rh.onPause();c({result:"Paused speech"});break;case "resume":Rh.onResume(),c({result:"Resumed speech"})}});return!0});
